/*
 * NNView.java
 *
 * Created on March 7, 2002, 9:56 PM
 */

/**
 *
 * @author  alson
 */
package uchicago.src.sim.nnheatBugs;


public class StringWindow extends javax.swing.JFrame {

    /** Creates new form NNView */
    public StringWindow(String DisplayString) {
        initComponents();
        jTextArea1.setText(DisplayString);
        jTextArea1.setCaretPosition(0);
        //pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 10));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });

        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // Add your handling code here:
        if (evt.getKeyChar() == evt.VK_ESCAPE )
            dispose();
    }//GEN-LAST:event_jTextArea1KeyTyped

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
